CaradaIdProvider.Web/Controllers/Mock/RpMockController.cs
using Microsoft.Azure;
using MTI.CaradaIdProvider.Web.Controllers.Web;
using MTI.CaradaIdProvider.Web.Logics;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.IdentityModel;
using System.IdentityModel.Tokens;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MTI.CaradaIdProvider.Web.Controllers.Mock
{
    /// <summary>
    /// テスト用のRPのモック。
    /// RouteConfigにて、デバッグ以外では無効になるように設定済み。
    /// </summary>
    public class RpMockController : BaseWebController
    {
        // 文字コード
        private static Encoding ENC = Encoding.UTF8;

        /// <summary>
        /// rsa
        /// </summary>
        private RSAEncryptor rsa = new RSAEncryptor(CloudConfigurationManager.GetSetting("PublicKey"));

        /// <summary>
        /// Authentication Request用モック。
        /// </summary>
        /// <returns>View</returns>
        public ActionResult Auth()
        {
            // クライアント情報を取得
            var clientData = (from cm in CaradaIdPDb.ClientMasters
                              where cm.ClientName == Properties.Settings.Default.AuthProviderClientName
                              select new { ClientId = cm.ClientId }).First();

            // Authentication Requestで送信するURLを設定
            var scheme = HttpContext.Request.Url.Scheme;
            var domain = HttpContext.Request.Url.Authority;
            ViewBag.request_url = scheme + "://" + domain + "/oauth2/auth";
            // client_id
            ViewBag.client_id = clientData.ClientId;
            // scope。固定値
            ViewBag.scope = "openid";
            // response_type。固定値
            ViewBag.response_type = "code";
            // redirect_uri
            ViewBag.redirect_uri = scheme + "://" + domain + "/RpMock/Token";
            // state。ランダム生成
            var state = Guid.NewGuid().ToString("N");
            ViewBag.state = state;

            Session["mockSession"] = state;

            return View("Auth");
        }

        /// <summary>
        /// Token Request用モック。
        /// Authentication Responseのredirect先を兼ねている。
        /// </summary>
        /// <param name="model">(RpMockModel</param>
        /// <returns>View</returns>
        public ActionResult Token(RpMockModel model)
        {
            // Authentication Requestで送信したものを取得。
            if (Session["mockSession"] != null)
            {
                model.request_state = Session["mockSession"] as String;
                Session.Remove("mockSession");
            }
            // Authentication Responseがエラーの場合はエラー用の画面を表示
            if (model.error != null)
            {
                return View("AuthError", model);

            }

            // Token Requestで送信するデフォルト値を設定
            var clientData = (from cm in CaradaIdPDb.ClientMasters
                              where cm.ClientName == Properties.Settings.Default.AuthProviderClientName
                              select new { ClientId = cm.ClientId, ClientSecret = cm.ClientSecret }).First();
            // grant_type。固定値
            model.grant_type = "authorization_code";
            // code : Authentication Responseの値をそのまま利用
            // redirect_uri
            var scheme = HttpContext.Request.Url.Scheme;
            var domain = HttpContext.Request.Url.Authority;
            model.redirect_uri = scheme + "://" + domain + "/RpMock/Token";
            // client_id
            model.client_id = clientData.ClientId;
            // client_secret
            model.client_secret = clientData.ClientSecret;
            return View("Token", model);
        }

        /// <summary>
        /// Token Requestをサーバー間通信として実行するモック。
        /// </summary>
        /// <param name="model">RpMockModel</param>
        /// <returns>Token Response結果のView</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RequestToken(RpMockModel model)
        {
            var scheme = HttpContext.Request.Url.Scheme;
            var domain = HttpContext.Request.Url.Authority;
            var url = scheme + "://" + domain + "/oauth2/token";

            // POST送信する文字列を作成
            var ht = new Hashtable();
            ht["grant_type"] = HttpUtility.UrlEncode(model.grant_type, ENC);
            ht["code"] = HttpUtility.UrlEncode(model.code, ENC);
            ht["redirect_uri"] = HttpUtility.UrlEncode(model.redirect_uri, ENC);
            ht["client_id"] = HttpUtility.UrlEncode(model.client_id, ENC);
            ht["client_secret"] = HttpUtility.UrlEncode(model.client_secret, ENC);

            var param = "";
            foreach (var k in ht.Keys)
            {
                param += String.Format("{0}={1}&", k, ht[k]);
            }
            byte[] postDataBytes = Encoding.ASCII.GetBytes(param);

            ServicePointManager.ServerCertificateValidationCallback
                = (sender, certificate, chain, sslPolicyErrors) => { return true; };

            // リクエストの作成
            var req = (HttpWebRequest)WebRequest.Create(url);
            req.Method = "POST";
            req.ContentType = "application/x-www-form-urlencoded; charset=utf-8";
            req.ContentLength = postDataBytes.Length;

            // 送信するデータを書き込む
            var reqStream = req.GetRequestStream();
            using (var sw = new StreamWriter(reqStream))
            {
                sw.Write(param);
            }

            // 受信して表示
            try
            {
                var res = (HttpWebResponse)req.GetResponse();
                var resStream = res.GetResponseStream();
                ViewBag.code = res.StatusCode;
                using (var sr = new StreamReader(resStream, ENC))
                {
                    string json = sr.ReadToEnd();
                    ViewBag.responseBody = json;
                    // Response BodyのJSON
                    var result = JsonConvert.DeserializeObject<TokenResponseJson>(json);
                    ViewBag.access_token = result.access_token;
                    ViewBag.token_type = result.token_type;
                    ViewBag.expires_in = result.expires_in;
                    ViewBag.id_token = result.id_token;

                    if (!string.IsNullOrEmpty(ViewBag.id_token))
                    {
                        // Token IDを可視化
                        // "."で連結されているので分離
                        string[] jwt = result.id_token.Split('.');
                        // JWTヘッダ部分
                        ViewBag.jwt_head = Base64UrlToUTF8(jwt[0]);
                        // JWT本文
                        var jwtBody = Base64UrlToUTF8(jwt[1]);
                        ViewBag.jwt_body = jwtBody;
                        var payloadJson = JsonConvert.DeserializeObject<IdTokenPayloadJson>(jwtBody);
                        ViewBag.iss = payloadJson.iss;
                        ViewBag.sub = payloadJson.sub;
                        ViewBag.aud = payloadJson.aud;
                        ViewBag.exp = payloadJson.exp;
                        ViewBag.iat = payloadJson.iat;

                        // 時間をエポック秒から変換
                        var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
                        var jstZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");

                        var expUtc = epoch.AddSeconds(payloadJson.exp);
                        var expJst = TimeZoneInfo.ConvertTimeFromUtc(expUtc, jstZoneInfo);
                        var iatUtc = epoch.AddSeconds(payloadJson.iat);
                        var iatJst = TimeZoneInfo.ConvertTimeFromUtc(iatUtc, jstZoneInfo);
                        ViewBag.exp_utc = expUtc;
                        ViewBag.exp_jst = expJst;
                        ViewBag.iat_utc = iatUtc;
                        ViewBag.iat_jst = iatJst;
                        var utcNow = DateTime.UtcNow;
                        ViewBag.now_utc = utcNow;
                        ViewBag.now_jst = TimeZoneInfo.ConvertTimeFromUtc(utcNow, jstZoneInfo);

                        // JWT署名
                        ViewBag.jwt_signature = jwt[2];

                        // 署名検証
                        ViewBag.jwt_verify = VerifySignature(result.id_token);
                    }
                }
            }
            catch (WebException ex)
            {
                //HTTPプロトコルエラーかどうか調べる
                if (ex.Status == System.Net.WebExceptionStatus.ProtocolError)
                {
                    // HTTPステータスコードとResponseBodyを取得
                    var errorRes = (HttpWebResponse)ex.Response;
                    ViewBag.code = errorRes.StatusCode;
                    var resStream = errorRes.GetResponseStream();
                    using (var sr = new StreamReader(resStream, ENC))
                    {
                        ViewBag.responseBody = sr.ReadToEnd();
                    }
                }
                else
                {
                    ViewBag.code = "Exception発生";
                    ViewBag.responseBody = ex.ToString();
                }
            }

            return View("TokenResponse");
        }

        private string Base64UrlToUTF8(string target)
        {
            var base64str = target.Replace('-', '+').Replace('_', '/');
            var lastBytes = base64str.Length % 4;
            if (lastBytes > 0)
            {
                base64str = base64str.PadRight(base64str.Length + 4 - lastBytes, '=');
            }

            return Encoding.UTF8.GetString(Convert.FromBase64String(base64str));
        }

        private bool VerifySignature(string idToken)
        {
            var parameters = new TokenValidationParameters()
            {
                IssuerSigningToken = new RsaSecurityToken(rsa.ToRSA()),
                ValidateActor = false,
                ValidateIssuer = false,
                ValidateAudience = false,
                ValidateLifetime = false
            };

            SecurityToken outToken;
            try
            {

CaradaIdProvider.Web/Views/RpMock/Auth.cshtml
@{
    ViewBag.Title = "RpMockAuth";
}

<h2>Authentication Requestモック</h2>
<br />
<form method="GET" action="@ViewBag.request_url" id="mock_form" name="mock_form">
    <div class="input-wrapper">
        <label class="label-bold" for="client_id">client_id</label>
        <input type="text" name="client_id" id="client_id" value="@ViewBag.client_id" />
    </div>
    <div class="input-wrapper">
        <label class="label-bold" for="scope">scope</label>
        <input type="text" name="scope" id="scope" value="@ViewBag.scope" />
    </div>
    <div class="input-wrapper">
        <label class="label-bold" for="response_type">response_type</label>
        <input type="text" name="response_type" id="response_type" value="@ViewBag.response_type" />
    </div>
    <div class="input-wrapper">
        <label class="label-bold" for="redirect_uri">redirect_uri</label>
        <input type="text" name="redirect_uri" id="redirect_uri" value="@ViewBag.redirect_uri" />
    </div>
    <div class="input-wrapper">
        <label class="label-bold" for="state">state</label>
        <input type="text" name="state" id="state" value="@ViewBag.state" />
    </div>
    <div class="btn-wrapper-02">
        <input type="button" name="authentication" id="authentication" value="送信" class="cp-btn-01">
    </div>
</form>

@section scripts{
    <script>
        // stateの値が存在しなければパラメータを削除する
        $(function () {
            $('#authentication').click(function () {
                if ($('#state').val() === '') {
                    $('#state').remove();
                }
                $('#mock_form').submit();
            });
        });
    </script>
}

CaradaIdProvider.Web/Views/RpMock/AuthError.cshtml
@model MTI.CaradaIdProvider.Web.Controllers.Mock.RpMockModel

@{
    ViewBag.Title = "AuthError";
}

<h2>Authentication Request Error</h2>
<br />
<div class="input-wrapper">
    error : [@Html.DisplayFor(model => model.error)]
</div>
<div class="input-wrapper">
    state : [@Html.DisplayFor(model => model.state)]<br />
    ※送信したstate ： [@Html.DisplayFor(model => model.request_state)]
</div>
<div class="input-wrapper">
    code : [@Html.DisplayFor(model => model.code)]<br />
    　※エラー時なので、この値は取得されないのが正常
</div>
<ul class="btn-group">
    <li>
        @Html.ActionLink("戻る", "Auth", "RpMock", null, new { @id = "Retrun", @class = "cp-btn-02" })
    </li>
</ul>

CaradaIdProvider.Web/Views/RpMock/Token.cshtml
@model MTI.CaradaIdProvider.Web.Controllers.Mock.RpMockModel

@{
    ViewBag.Title = "Token Request";
}

<h2>Successful Authentication Response</h2>
<br />
<div class="input-wrapper" id="receiveCode">
    code : [@Html.DisplayFor(model => model.code)]<br />
</div>
<div class="input-wrapper" id="receiveState">
    state : [@Html.DisplayFor(model => model.state)]<br />
</div>
<div class="input-wrapper" id="sendState">
    ※前画面で自動生成したstate（参考） ： [@Html.DisplayFor(model => model.request_state)]<br />
    入力値を変えた場合は違う値になります。
</div>
<br />
<h2>Token Request</h2>
@using (Html.BeginForm("RequestToken", "RpMock", FormMethod.Post, new { @class = "cp-form" }))
{
    @Html.AntiForgeryToken()
    <div class="input-wrapper">
        grant_type : @Html.TextBoxFor(model => model.grant_type)<br />
    </div>
    <div class="input-wrapper">
        code : @Html.TextBoxFor(model => model.code)<br />
    </div>
    <div class="input-wrapper">
        redirect_uri : @Html.TextBoxFor(model => model.redirect_uri)<br />
    </div>
    <div class="input-wrapper">
        client_id : @Html.TextBoxFor(model => model.client_id)<br />
    </div>
    <div class="input-wrapper">
        client_secret : @Html.TextBoxFor(model => model.client_secret)<br />
    </div>
    <div class="btn-wrapper-02">
        <input type="submit" name="token" value="送信" class="cp-btn-01">
    </div>}

CaradaIdProvider.Web/Views/RpMock/TokenResponse.cshtml
@{
    ViewBag.Title = "TokenResponse";
}

<h2>Token Response</h2>
<br />
<div class="input-wrapper">
    HTTPステータスコード : [@ViewBag.code]
</div>
<div class="input-wrapper">
    ResponseBody : [@ViewBag.responseBody]
</div>
<br />
<h3>Response Body JSON</h3>
<div class="input-wrapper">
    access_token : [@ViewBag.access_token]<br/>
    ※アクセストークン
</div>
<div class="input-wrapper">
    token_type : [@ViewBag.token_type]<br />
    ※"bearer"固定(ただし大文字小文字は区別しない)
</div>
<div class="input-wrapper">
    expires_in : [@ViewBag.expires_in]<br />
    ※アクセストークンの有効期限を示す秒数
</div>
<div class="input-wrapper">
    id_token : [@ViewBag.id_token]<br />
    ※ID Token
</div>
<br />
<h3>ID Token</h3>
<div class="input-wrapper">
    JWT署名検証OK?：[@ViewBag.jwt_verify]
</div>
<div class="input-wrapper">
    JWTヘッダ : [@ViewBag.jwt_head]
</div>
<div class="input-wrapper">
    JWT署名 : [@ViewBag.jwt_signature]
</div>
<div class="input-wrapper">
    JWT本文 : [@ViewBag.jwt_body]
</div>
<div class="input-wrapper">
    iss : [@ViewBag.iss]<br />
    ※Issuer ID。OPを示すURL
</div>
<div class="input-wrapper">
    sub : [@ViewBag.sub]<br />
    ※Subject ID。ユーザーを一意に識別するID
</div>
<div class="input-wrapper">
    aud : [@ViewBag.aud]<br />
    ※audience。client_idと同値となる
</div>
<div class="input-wrapper">
    exp : [@ViewBag.exp]<br />
    ※ID Tokenの有効期限。UTCのエポック秒<br />
    　exp UTC : [@ViewBag.exp_utc]<br />
    　exp JST : [@ViewBag.exp_jst]
</div>
<div class="input-wrapper">
    iat : [@ViewBag.iat]<br />
    ※JWT発行時刻。UTCのエポック秒<br />
    　iat UTC : [@ViewBag.iat_utc]<br />
    　iat JST : [@ViewBag.iat_jst]
</div>
<div class="input-wrapper">
    参考<br />
    　現在日時(UTC)： [@ViewBag.now_utc]<br />
    　現在日時(JST)： [@ViewBag.now_jst]<br />
</div>
<ul class="btn-group">
    <li>
        @Html.ActionLink("戻る", "Auth", "RpMock", null, new { @id = "Retrun", @class = "cp-btn-02" })
    </li>
</ul>