CaradaIdProvider.Web/Models/ViewModels/EmailChangeVerifyCodeViewModel.cs
using MTI.CaradaIdProvider.Web.Resource;
using System.ComponentModel.DataAnnotations;

namespace MTI.CaradaIdProvider.Web.Models.ViewModels
{
    /// <summary>
    /// メールアドレス変更認証画面のモデル
    /// </summary>
    public class EmailChangeVerifyCodeViewModel
    {
        /// <summary>
        /// 認証コード
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Text)]
        [Display(Name = "認証コード")]
        public string VerifyCode { get; set; }
    }
}

CaradaIdProvider.Web/Models/ViewModels/EmailChangeViewModel.cs
using MTI.CaradaIdProvider.Web.Models.ViewModels.DataAnnotations;
using MTI.CaradaIdProvider.Web.Resource;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MTI.CaradaIdProvider.Web.Models.ViewModels
{
    /// <summary>
    /// メールアドレス変更入力画面のモデル
    /// </summary>
    [Serializable]
    public class EmailChangeViewModel
    {
        /// <summary>
        /// 現在のメールアドレス
        /// 表示用。
        /// </summary>
        [Display(Name = "現在のメールアドレス")]
        public string Email { get; set; }

        /// <summary>
        /// 新しいメールアドレス
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [MaxLength(255, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "MaxLength")]
        [EmailAddressJP(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "EmailFormat", ErrorMessage = null)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "新しいメールアドレス")]
        public string NewEmail { get; set; }

        /// <summary>
        /// パスワード
        /// </summary>
        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Password)]
        [Display(Name = "パスワード")]
        public string Password { get; set; }
    }
}

CaradaIdProvider.Web/Models/ViewModels/EmailResetVerifyCodeViewModel.cs
using MTI.CaradaIdProvider.Web.Resource;
using System.ComponentModel.DataAnnotations;

namespace MTI.CaradaIdProvider.Web.Models.ViewModels
{
    /// <summary>
    /// メールアドレス再設定認証画面のモデル
    /// </summary>
    public class EmailResetVerifyCodeViewModel
    {
        /// <summary>
        /// 認証コード
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Text)]
        [Display(Name = "認証コード")]
        public string VerifyCode { get; set; }
    }
}

CaradaIdProvider.Web/Models/ViewModels/EmailResetViewModel.cs
using MTI.CaradaIdProvider.Web.Models.ViewModels.DataAnnotations;
using MTI.CaradaIdProvider.Web.Resource;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MTI.CaradaIdProvider.Web.Models.ViewModels
{
    /// <summary>
    /// メールアドレス再設定画面のモデル
    /// </summary>
    [Serializable]
    public class EmailResetViewModel
    {
        /// <summary>
        /// CARADA ID
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [Display(Name = "CARADA ID")]
        public string CaradaId { get; set; }

        /// <summary>
        /// パスワード
        /// </summary>
        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Password)]
        [Display(Name = "パスワード")]
        public string Password { get; set; }

        /// <summary>
        /// 秘密の質問選択ID
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [RegularExpression(@"^[0-9]+$", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "NumberError")]
        [Display(Name = "秘密の質問")]
        public int? SecurityQuestionSelectId { get; set; }

        /// <summary>
        /// 答え
        /// </summary>
        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [MaxLength(50, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "SecurityQuestionAnswerChar")]
        [SecurityAnswer(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "SecurityQuestionAnswerChar")]
        [Display(Name = "答え")]
        public string Answer { get; set; }

        /// <summary>
        /// 新しいメールアドレス
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [MaxLength(255, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "MaxLength")]
        [EmailAddressJP(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "EmailFormat", ErrorMessage = null)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "新しいメールアドレス")]
        public string Email { get; set; }

        /// <summary>
        /// SelectListItemのキーと値の辞書
        /// </summary>
        /// <remarks>
        /// SelectListItemがSerializableでないため、TempDataへの保持用として定義する.
        /// 単なるGetter,SetterなのでUTなし.
        /// </remarks>
        public Dictionary<int, string> SerializeItems { get; set; }
    }
}

CaradaIdProvider.Web/Models/ViewModels/PasswordChangeViewModel.cs
using MTI.CaradaIdProvider.Web.Models.ViewModels.DataAnnotations;
using MTI.CaradaIdProvider.Web.Resource;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MTI.CaradaIdProvider.Web.Models.ViewModels
{
    /// <summary>
    /// パスワード変更画面のモデル
    /// </summary>
    [Serializable]
    public class PasswordChangeViewModel
    {
        /// <summary>
        /// 現在のパスワード
        /// </summary>
        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Password)]
        [Display(Name = "現在のパスワード")]
        public string CurrentPassword { get; set; }

        /// <summary>
        /// 新パスワード
        /// </summary>
        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [MinLength(8, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "MinLength")]
        [MaxLength(128, ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "MaxLength")]
        [PasswordCombine(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "PasswordCombine", ErrorMessage = null)]
        [RegularExpression(@"^[0-9a-zA-Z!-/:-@\[-\`\{-\~]{1,}$", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "ChangePasswordChar")]
        [DataType(DataType.Password)]
        [Display(Name = "新しいパスワード")]
        public string NewPassword { get; set; }

        /// <summary>
        /// 新パスワード（確認用）
        /// </summary>
        [AllowHtml]
        [Required(ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Required")]
        [System.ComponentModel.DataAnnotations.Compare("NewPassword", ErrorMessageResourceType = typeof(ErrorMessages), ErrorMessageResourceName = "Compare")]
        [DataType(DataType.Password)]
        [Display(Name = "新しいパスワード（確認用）")]
        public string NewPasswordConfirm { get; set; }
    }
}

CaradaIdProvider.Web/Controllers/Web/UserSettingsController.cs
using Microsoft.AspNet.Identity;
using MTI.CaradaIdProvider.Web.DataBase.Entities;
using MTI.CaradaIdProvider.Web.IdentityManagers;
using MTI.CaradaIdProvider.Web.Logics;
using MTI.CaradaIdProvider.Web.Models.ViewModels;
using MTI.CaradaIdProvider.Web.Resource;
using MTI.CaradaIdProvider.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MTI.CaradaIdProvider.Web.Controllers.Web
{
    /// <summary>
    /// ユーザー設定コントローラー
    /// </summary>
    public class UserSettingsController : BaseWebController
    {
        /// <summary>
        /// メールアドレス再設定画面のTempData名
        /// </summary>
        private const string EmailResetTemp = "EmailReset";

        /// <summary>
        /// メールアドレス変更画面のTempData名
        /// </summary>
        private const string EmailChangeTemp = "EmailChange";

        /// <summary>
        /// 秘密の質問変更画面のTempData名
        /// </summary>
        private const string SecurityQuestionChangeTemp = "SecurityQuestionChange";

        /// <summary>
        /// ユーザーIDのTempData名
        /// </summary>
        private const string UserIdTemp = "UserId";

        /// <summary>
        /// ハッシュコンバーター
        /// </summary>
        private HashConverter hashConverter = new HashConverter();

        /// <summary>
        /// 二段階認証
        /// </summary>
        private TwoFactorAuthenticator twoFactorAuthenticator = new TwoFactorAuthenticator();

        /// <summary>
        /// アカウント管理画面を初期表示する。
        /// </summary>
        /// <returns>アカウント管理画面のViewResult</returns>
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Index()
        {
            // ※戻るボタンで戻った時用の処理。
            TempData.Clear();

            // ユーザー情報取得
            var user = await GetRegisteredSignInUser(true);

            // 秘密の質問の回答を取得
            var selectAnswer = (from c in CaradaIdPDb.SecurityQuestionAnswers
                                where c.UserId == user.Id
                                select c).ToList();
            if (selectAnswer.Count != 1)
            {
                // ログイン状態が不正になる場合があるので、サインアウトしておく
                await SignInManager.SignOut();
                throw new HttpException("SecurityQuestionAnswers must unique per user.");
            }

            var securityQuestionId = selectAnswer[0].SecurityQuestionId;

            // 秘密の質問を取得
            var question = (from c in CaradaIdPDb.SecurityQuestionMasters
                            where c.SecurityQuestionId == securityQuestionId
                            select c).FirstOrDefault();
            if (question == null)
            {
                // ログイン状態が不正になる場合があるので、サインアウトしておく
                await SignInManager.SignOut();
                throw new HttpException("Such SecurityQuestion does not exitsts.");
            }

            var userSettingsModel = new UserSettingsViewModel()
            {
                CaradaId = user.UserName,
                Email = user.Email,
                SecurityQuestion = question.Question
            };

            return View(userSettingsModel);
        }

        /// <summary>
        /// メールアドレス再設定画面 表示アクション
        /// </summary>
        /// <returns>画面ViewResult</returns>
        [HttpGet]
        public ActionResult EmailResetView()
        {
            // 入力情報があれば取得
            var emailResetViewModel = TempData[EmailResetTemp] as EmailResetViewModel;
            if (emailResetViewModel == null)
            {
                emailResetViewModel = new EmailResetViewModel();
            }
            else
            {
                emailResetViewModel.SecurityQuestionSelectId = null;
                emailResetViewModel.Password = null;
                emailResetViewModel.Answer = null;
            }

            emailResetViewModel.SerializeItems = SelectListUtility.ConvertSelectListToDic(GetSecurityQuestion());

            TempData[EmailResetTemp] = emailResetViewModel;

            return View("EmailReset", emailResetViewModel);
        }

        /// <summary>
        /// 秘密の質問リストを取得する
        /// </summary>
        /// <returns>秘密の質問リスト</returns>
        private List<SelectListItem> GetSecurityQuestion()
        {
            var query = (from c in CaradaIdPDb.SecurityQuestionMasters
                         orderby c.DisplayOrder
                         select c).ToList();
            return query.Select(t => new SelectListItem
            {
                Text = t.Question,
                Value = t.SecurityQuestionId.ToString()
            })
            .ToList();
        }

        /// <summary>
        /// ユーザに紐づいた秘密の質問の回答を取得する
        /// </summary>
        /// <param name="userId">ユーザID</param>
        /// <returns>秘密の質問の回答</returns>
        private SecurityQuestionAnswers GetSecurityAnswer(string userId)
        {
            var selectAnswer = (from c in CaradaIdPDb.SecurityQuestionAnswers
                                where c.UserId == userId
                                select c).ToList();
            // Note: 基本的に0になることはユーザ削除時しかない。
            // また、現在の仕様では複数の紐づけは認めていない。
            if (selectAnswer.Count != 1)
            {
                throw new HttpException("SecurityQuestionAnswers must unique per user.");
            }
            return selectAnswer[0];
        }

        /// <summary>
        /// メールアドレス再設定画面 再設定アクション
        /// </summary>
        /// <param name="model">EmailResetViewModel</param>
        /// <returns>エラー：メールアドレス再設定画面のViewResult, 正常：メールアドレス再設定認証画面のViewResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EmailReset([Bind(Include = "CaradaId,Password,SecurityQuestionSelectId,Answer,Email")] EmailResetViewModel model)
        {
            var userByCaradaId = await UserManager.FindByNameAsync(model.CaradaId);

            // ユーザー情報が取得できないか利用開始登録されていない場合、画面を再表示する。
            if (userByCaradaId == null)
            {
                LOG.Warn("ID・パスワードが正しくありません");
                ModelState.AddModelError("CaradaId", ErrorMessages.LoginError);
                return View(model);
            }
            else if (!userByCaradaId.EmailConfirmed)
            {
                LOG.Warn("利用開始前のユーザーです");
                ModelState.AddModelError("CaradaId", ErrorMessages.NotProcessedUseStart);

                return View(model);
            }

            // パスワードの妥当性検証（ログイン成功時失敗回数更新はしない）
            if (!await ValidatePasswordNotCountReset(userByCaradaId, model.Password, "CaradaId"))
            {
                return View(model);
            }

            // 秘密の質問の回答を検索
            var selectAnswer = (from c in CaradaIdPDb.SecurityQuestionAnswers
                                where c.UserId == userByCaradaId.Id && c.SecurityQuestionId == model.SecurityQuestionSelectId
                                select c).FirstOrDefault();

            if (selectAnswer == null || selectAnswer.Answer != hashConverter.ConvertString(model.Answer))
            {
                // 秘密の質問回答誤り 失敗回数のカウントアップをする
                await UserManager.AccessFailedAsync(userByCaradaId.Id);

                LOG.Warn("秘密の質問と回答が正しくありません");

                if (await UserManager.IsLockedOutAsync(userByCaradaId.Id))
                {
                    // ロックされる失敗回数に到達した時点でロック中とする
                    LOG.Error("アカウントロックアウト開始");
                    ModelState.AddModelError("Answer", ErrorMessages.SettingsLockOut);
                    return View(model);
                }

                ModelState.AddModelError("Answer", ErrorMessages.VerifySecurityQuestionAnswer);
                return View(model);
            }

            // ログイン失敗回数をリセットする
            await UserManager.ResetAccessFailedCountAsync(userByCaradaId.Id);

            // メールアドレスの確認
            var userByEmail = await UserManager.FindByEmailAsync(model.Email);

            if (userByEmail != null)
            {

                // CARADA IDとメールアドレスのユーザー情報が一致する場合
                if (userByCaradaId == userByEmail)
                {
                    // メールアドレス変更不要エラー
                    LOG.Warn("現在のメールアドレスと同じメールアドレスが入力されました");
                    ModelState.AddModelError("Email", string.Format(ErrorMessages.MustNotSame, "メールアドレス", "現在のメールアドレス"));
                    return View(model);
                }

                if (userByEmail.EmailConfirmed)
                {
                    // 登録済みメールアドレスエラー
                    LOG.Warn("メールアドレスは別のユーザーが使用済みです");
                    ModelState.AddModelError("Email", ErrorMessages.RegisteredMail);
                    return View(model);
                }
            }

            // ユーザ情報の更新
            userByCaradaId.AuthCodeFailedCount = 0;
            userByCaradaId.AuthCodeExpireDateUtc = DateTime.UtcNow.AddMinutes(ApplicationUserManager.VERIFY_CODE_EXPIRE_MINUTES);
            await UserManager.UpdateAsync(userByCaradaId);

            // セキュリティタイムスタンプ更新
            await UserManager.UpdateSecurityStampAsync(userByCaradaId.Id);

            // 認証コード生成
            var code = await UserManager.GenerateTwoFactorTokenAsync(userByCaradaId.Id, Properties.Settings.Default.EmailResetSendCodeProvider);

            // メールオブジェクト作成
            var message = new IdentityMessage
            {
                Body = string.Format(Mail.EmailResetSendCodeBody.Replace(":SUPPORT:", Mail.Support), code),
                Subject = Mail.EmailResetSendCodeSubject,
                Destination = model.Email
            };

            // 認証コード案内メールを送信
            await UserManager.EmailService.SendAsync(message);

            // 入力フォームの値をTempDataに入れる。
            TempData[EmailResetTemp] = model;

            // メールアドレス再設定認証画面に遷移する。
            return View("EmailResetVerifyCode");
        }

        /// <summary>
        /// メールアドレス再設定認証画面 認証するアクション
        ///  認証コードが妥当な場合、新旧メールアドレスへ完了メール送信し、ログイン画面へ遷移する。
        /// </summary>

CaradaIdProvider.Web/Views/UserSettings/EmailChange.cshtml
@using MTI.CaradaIdProvider.Web.Models.ViewModels
@model MTI.CaradaIdProvider.Web.Models.ViewModels.EmailChangeViewModel
@{
    ViewBag.Title = "メールアドレス変更";
    ViewBag.Url = "/UserSettings/EmailChange";

    var emailChangeTemp = TempData["EmailChange"] as EmailChangeViewModel;
    TempData.Keep();
}
<h1 class="h2">CARADA ID メールアドレス変更</h1>
<p class="margin-30">メールアドレスの変更を行います。<br>新しく設定されるメールアドレスと、本人認証の為に、登録されたパスワードをご入力ください。</p>
@using (Html.BeginForm("EmailChange", "UserSettings", FormMethod.Post, new { @class = "form-horizontal", @autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="col-sm-3 control-label">@Html.DisplayNameFor(model => model.Email)</label>
        <div class="col-sm-9">
            <span class="form-control no-input" id="Email">@emailChangeTemp.Email</span>
        </div>
    </div>
    <div class="form-group">
        <label for="NewEmail" class="col-sm-3 control-label">@Html.DisplayNameFor(model => model.NewEmail)</label>
        <div class="col-sm-9">
            @Html.EditorFor(model => model.NewEmail, new { htmlAttributes = new { @type = "email", @class = "form-control", @data_rule_email = "false", @placeholder = "新しいメールアドレス" } })
            <span class="text-danger">@Html.ValidationMessageFor(model => model.NewEmail)</span>
        </div>
    </div>
    <div class="form-group">
        <label for="Password" class="col-sm-3 control-label">@Html.DisplayNameFor(model => model.Password)</label>
        <div class="col-sm-9">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type = "password", @class = "form-control", @placeholder = "パスワード" } })
            <span class="text-danger">@Html.ValidationMessageFor(model => model.Password)</span>
        </div>
    </div>
    <div class="form-group margin-20">
        <div class="col-sm-9 col-sm-offset-3">
            <ul class="indent">
                <li class="caution"><small>ドメイン指定受信をご利用の方は、「@@carada.jp」 のドメイン解除設定をお願いいたします。</small></li>
            </ul>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-push-5 col-sm-5 col-md-push-5 col-md-4 margin-10">
            <button type="submit" class="btn btn-lg btn-primary btn-block" name="Change">変更する</button>
        </div>
        <div class="col-sm-pull-2 col-sm-2 col-md-pull-1 col-md-2">
            @Html.ActionLink("戻る", "Index", "UserSettings", null, new { @id = "Back", @class = "btn btn-lg btn-cancel btn-block" })
        </div>
    </div>
}

CaradaIdProvider.Web/Views/UserSettings/EmailChange.fp.cshtml
@using MTI.CaradaIdProvider.Web.Models.ViewModels
@model MTI.CaradaIdProvider.Web.Models.ViewModels.EmailChangeViewModel
@{
    ViewBag.Title = "ﾒｰﾙｱﾄﾞﾚｽ変更";
    ViewBag.Url = "/UserSettings/EmailChange";

    var emailChangeTemp = TempData["EmailChange"] as EmailChangeViewModel;
    TempData.Keep();
}
<div style="background-color:#313131;color:white;font-size:small;">
    CARADA ID ﾒｰﾙｱﾄﾞﾚｽ変更
</div>
<br />
ﾒｰﾙｱﾄﾞﾚｽの変更を行います｡<br />
新しく設定されるﾒｰﾙｱﾄﾞﾚｽと､本人認証の為に､登録されたﾊﾟｽﾜｰﾄﾞをご入力ください｡<br />
<br />
@using (Html.BeginForm("EmailChange", "UserSettings", FormMethod.Post, new { @autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    <div align="left">
        現在のﾒｰﾙｱﾄﾞﾚｽ<br /><br />
        @emailChangeTemp.Email<br /><br />
        新しいﾒｰﾙｱﾄﾞﾚｽ<br />
        <div align="left">
            @Html.EditorFor(model => model.NewEmail, new { htmlAttributes = new { @style="width:100% ", @type="text", @istyle="3" } })
        </div>
        <span style="color:#a94442;">@Html.ValidationMessageFor(model => model.NewEmail)</span>
        <br />
        ﾊﾟｽﾜｰﾄﾞ<br />
        <div align="left">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @style = "width:100%", @type = "password", @istyle = "3" } })
        </div>
        <span style="color:#a94442;">@Html.ValidationMessageFor(model => model.Password)</span>
        <br />
        @("※ﾄﾞﾒｲﾝ指定受信をご利用の方は､｢@carada.jp｣のﾄﾞﾒｲﾝ解除設定をお願いいたします｡")
        <br />
        <br />
        <div align="center"><input type="submit" value="    変更する    " name="Change"/></div>
        <br />
        @Html.ActionLink("戻る", "Index", "UserSettings", null, new { @id = "Back" })
    </div>
}

CaradaIdProvider.Web/Views/UserSettings/EmailChangeConfirm.cshtml
@{
    ViewBag.Title = "メールアドレス変更確認";
    ViewBag.Url = "/UserSettings/EmailChangeConfirm";
}
<h1 class="h2">CARADA ID メールアドレス変更確認</h1>
<p class="margin-30">入力内容をご確認の上、登録ボタンから完了させてください。</p>
@using (Html.BeginForm("EmailChangeConfirm", "UserSettings", FormMethod.Post, new { @autocomplete = "off", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="col-sm-3 control-label" for="NewEmail">新しいメールアドレス</label>
        <div class="col-sm-9">
            <span class="form-control no-input" id="NewEmail">@ViewBag.NewEmail</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-push-5 col-sm-5 col-md-push-5 col-md-4 margin-10">
            <button type="submit" class="btn btn-lg btn-primary btn-block" value="登録する" name="Confirm">登録する</button>
        </div>
        <div class="col-sm-pull-2 col-sm-2 col-md-pull-1 col-md-2">
            @Html.ActionLink("修正する", "EmailChangeView", "UserSettings", null, new { @id = "Edit", @class = "btn btn-lg btn-cancel btn-block" })
        </div>
    </div>
}

CaradaIdProvider.Web/Views/UserSettings/EmailChangeConfirm.fp.cshtml
@{
    ViewBag.Title = "ﾒｰﾙｱﾄﾞﾚｽ変更確認";
    ViewBag.Url = "/UserSettings/EmailChangeConfirm";
}
<div style="background-color:#313131;color:white;font-size:small;">
CARADA ID ﾒｰﾙｱﾄﾞﾚｽ変更確認
</div>
<br />
入力内容をご確認の上､登録ﾎﾞﾀﾝから完了させてください｡<br />
<br />
<div>
    新しいﾒｰﾙｱﾄﾞﾚｽ<br /><br />
    @ViewBag.NewEmail<br />
</div><br />
<div align="center">
    @using (Html.BeginForm("EmailChangeView", "UserSettings", FormMethod.Get, new { @name = "modify", @id = "modify" }))
    {
        <input type="submit" value="    修正する    " id="Edit" />
    }
    <br />
    @using (Html.BeginForm("EmailChangeConfirm", "UserSettings", FormMethod.Post, new { @name = "regist", @id = "regist" }))
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="    登録する    " name="Confirm" />
    }
</div>

CaradaIdProvider.Web/Views/UserSettings/PasswordResetGuide.fp.cshtml
@model MTI.CaradaIdProvider.Web.Models.ViewModels.PasswordResetGuideViewModel
@{
    ViewBag.Title = "ﾊﾟｽﾜｰﾄﾞ再設定案内";
    ViewBag.Url = "/UserSettings/PasswordResetGuide";
}
<div style="background-color:#313131;color:white;font-size:small;">
    CARADA ID ﾊﾟｽﾜｰﾄﾞ再設定案内
</div>
<br />
    ﾊﾟｽﾜｰﾄﾞ再設定のご案内をﾒｰﾙにて送信させていただきます｡<br />
    登録されているﾒｰﾙｱﾄﾞﾚｽを入力してください｡<br />
<br />
@using (Html.BeginForm("PasswordResetGuide", "UserSettings", FormMethod.Post, new { }))
{
    @Html.AntiForgeryToken()
    @("ﾒｰﾙｱﾄﾞﾚｽ")
    <div align="left">
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @style = "width:100%", @type = "text", @istyle = "3" } })
    </div>
        <span style="color:#a94442;">@Html.ValidationMessageFor(model => model.Email)</span>
        <br />
        @("※ﾄﾞﾒｲﾝ指定受信をご利用の方は､｢@carada.jp｣")
        <br />
        @("のﾄﾞﾒｲﾝ解除設定をお願いいたします｡")
        <br />
        <br />
        <div style="text-align:center;">
            <input type="submit" value="    ﾊﾟｽﾜｰﾄﾞを再設定する    " name="Reset" />
        </div>
}
<br />
@Html.ActionLink("戻る", "LoginView", "User", null, new { @id = "Back" })